// Code generated by protoc-gen-go. DO NOT EDIT.
// source: XXXLoginServer.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NoArgReq
type NoArgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoArgRequest) Reset()         { *m = NoArgRequest{} }
func (m *NoArgRequest) String() string { return proto.CompactTextString(m) }
func (*NoArgRequest) ProtoMessage()    {}
func (*NoArgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{0}
}

func (m *NoArgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoArgRequest.Unmarshal(m, b)
}
func (m *NoArgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoArgRequest.Marshal(b, m, deterministic)
}
func (m *NoArgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoArgRequest.Merge(m, src)
}
func (m *NoArgRequest) XXX_Size() int {
	return xxx_messageInfo_NoArgRequest.Size(m)
}
func (m *NoArgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoArgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoArgRequest proto.InternalMessageInfo

// NoReply
type NoReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoReply) Reset()         { *m = NoReply{} }
func (m *NoReply) String() string { return proto.CompactTextString(m) }
func (*NoReply) ProtoMessage()    {}
func (*NoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{1}
}

func (m *NoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoReply.Unmarshal(m, b)
}
func (m *NoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoReply.Marshal(b, m, deterministic)
}
func (m *NoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoReply.Merge(m, src)
}
func (m *NoReply) XXX_Size() int {
	return xxx_messageInfo_NoReply.Size(m)
}
func (m *NoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NoReply.DiscardUnknown(m)
}

var xxx_messageInfo_NoReply proto.InternalMessageInfo

type SendVerifyCodeReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerifyCodeReq) Reset()         { *m = SendVerifyCodeReq{} }
func (m *SendVerifyCodeReq) String() string { return proto.CompactTextString(m) }
func (*SendVerifyCodeReq) ProtoMessage()    {}
func (*SendVerifyCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{2}
}

func (m *SendVerifyCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerifyCodeReq.Unmarshal(m, b)
}
func (m *SendVerifyCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerifyCodeReq.Marshal(b, m, deterministic)
}
func (m *SendVerifyCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerifyCodeReq.Merge(m, src)
}
func (m *SendVerifyCodeReq) XXX_Size() int {
	return xxx_messageInfo_SendVerifyCodeReq.Size(m)
}
func (m *SendVerifyCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerifyCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerifyCodeReq proto.InternalMessageInfo

func (m *SendVerifyCodeReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type SendVerifyCodeReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Vcode                string   `protobuf:"bytes,3,opt,name=vcode,proto3" json:"vcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerifyCodeReply) Reset()         { *m = SendVerifyCodeReply{} }
func (m *SendVerifyCodeReply) String() string { return proto.CompactTextString(m) }
func (*SendVerifyCodeReply) ProtoMessage()    {}
func (*SendVerifyCodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{3}
}

func (m *SendVerifyCodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerifyCodeReply.Unmarshal(m, b)
}
func (m *SendVerifyCodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerifyCodeReply.Marshal(b, m, deterministic)
}
func (m *SendVerifyCodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerifyCodeReply.Merge(m, src)
}
func (m *SendVerifyCodeReply) XXX_Size() int {
	return xxx_messageInfo_SendVerifyCodeReply.Size(m)
}
func (m *SendVerifyCodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerifyCodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerifyCodeReply proto.InternalMessageInfo

func (m *SendVerifyCodeReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SendVerifyCodeReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendVerifyCodeReply) GetVcode() string {
	if m != nil {
		return m.Vcode
	}
	return ""
}

type LoginReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	DeviceType           string   `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	VerifyCode           string   `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginReq) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *LoginReq) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

type LoginReplyData struct {
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ExpireTs             int64    `protobuf:"varint,5,opt,name=expire_ts,json=expireTs,proto3" json:"expire_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReplyData) Reset()         { *m = LoginReplyData{} }
func (m *LoginReplyData) String() string { return proto.CompactTextString(m) }
func (*LoginReplyData) ProtoMessage()    {}
func (*LoginReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{5}
}

func (m *LoginReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReplyData.Unmarshal(m, b)
}
func (m *LoginReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReplyData.Marshal(b, m, deterministic)
}
func (m *LoginReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReplyData.Merge(m, src)
}
func (m *LoginReplyData) XXX_Size() int {
	return xxx_messageInfo_LoginReplyData.Size(m)
}
func (m *LoginReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReplyData proto.InternalMessageInfo

func (m *LoginReplyData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginReplyData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReplyData) GetExpireTs() int64 {
	if m != nil {
		return m.ExpireTs
	}
	return 0
}

type LoginReply struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *LoginReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{6}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginReply) GetData() *LoginReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerifyTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceType           string   `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenReq) Reset()         { *m = VerifyTokenReq{} }
func (m *VerifyTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenReq) ProtoMessage()    {}
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{7}
}

func (m *VerifyTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenReq.Unmarshal(m, b)
}
func (m *VerifyTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenReq.Merge(m, src)
}
func (m *VerifyTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenReq.Size(m)
}
func (m *VerifyTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenReq proto.InternalMessageInfo

func (m *VerifyTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VerifyTokenReq) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *VerifyTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenReply struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ExpireTs             int64    `protobuf:"varint,2,opt,name=expire_ts,json=expireTs,proto3" json:"expire_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenReply) Reset()         { *m = VerifyTokenReply{} }
func (m *VerifyTokenReply) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenReply) ProtoMessage()    {}
func (*VerifyTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2188abdff4ff6362, []int{8}
}

func (m *VerifyTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenReply.Unmarshal(m, b)
}
func (m *VerifyTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenReply.Marshal(b, m, deterministic)
}
func (m *VerifyTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenReply.Merge(m, src)
}
func (m *VerifyTokenReply) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenReply.Size(m)
}
func (m *VerifyTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenReply proto.InternalMessageInfo

func (m *VerifyTokenReply) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *VerifyTokenReply) GetExpireTs() int64 {
	if m != nil {
		return m.ExpireTs
	}
	return 0
}

func init() {
	proto.RegisterType((*NoArgRequest)(nil), "community.interface.XXXLoginServer.NoArgRequest")
	proto.RegisterType((*NoReply)(nil), "community.interface.XXXLoginServer.NoReply")
	proto.RegisterType((*SendVerifyCodeReq)(nil), "community.interface.XXXLoginServer.SendVerifyCodeReq")
	proto.RegisterType((*SendVerifyCodeReply)(nil), "community.interface.XXXLoginServer.SendVerifyCodeReply")
	proto.RegisterType((*LoginReq)(nil), "community.interface.XXXLoginServer.LoginReq")
	proto.RegisterType((*LoginReplyData)(nil), "community.interface.XXXLoginServer.LoginReplyData")
	proto.RegisterType((*LoginReply)(nil), "community.interface.XXXLoginServer.LoginReply")
	proto.RegisterType((*VerifyTokenReq)(nil), "community.interface.XXXLoginServer.VerifyTokenReq")
	proto.RegisterType((*VerifyTokenReply)(nil), "community.interface.XXXLoginServer.VerifyTokenReply")
}

func init() { proto.RegisterFile("XXXLoginServer.proto", fileDescriptor_2188abdff4ff6362) }

var fileDescriptor_2188abdff4ff6362 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0xdc, 0xb4, 0x4d, 0x3f, 0x5e, 0x51, 0x04, 0x66, 0x05, 0xa1, 0x1c, 0x40, 0x3e, 0x21, 0x81,
	0x72, 0x28, 0x20, 0xce, 0x7c, 0x08, 0x09, 0x84, 0xf6, 0x90, 0xad, 0x56, 0x05, 0x21, 0x05, 0x6f,
	0xfd, 0xb6, 0xb2, 0x48, 0x63, 0xd7, 0x76, 0x23, 0x7c, 0xdd, 0x7f, 0xcd, 0x0d, 0xc5, 0xe9, 0x2e,
	0x35, 0x48, 0x6c, 0xcb, 0xad, 0x63, 0xcd, 0xf3, 0xcc, 0x9b, 0x71, 0x03, 0xc7, 0xf3, 0xf9, 0xfc,
	0x93, 0x5c, 0x8a, 0xea, 0x14, 0x75, 0x8d, 0x3a, 0x53, 0x5a, 0x5a, 0x49, 0xe8, 0x42, 0xae, 0x56,
	0x9b, 0x4a, 0x58, 0x97, 0x89, 0xca, 0xa2, 0xbe, 0x60, 0x0b, 0xcc, 0x42, 0x26, 0x4d, 0xe0, 0xd6,
	0x89, 0x7c, 0xad, 0x97, 0x39, 0xae, 0x37, 0x68, 0x2c, 0x1d, 0xc1, 0xe0, 0x44, 0xe6, 0xa8, 0x4a,
	0x47, 0x9f, 0xc2, 0x9d, 0x53, 0xac, 0xf8, 0x19, 0x6a, 0x71, 0xe1, 0xde, 0x4a, 0x8e, 0x39, 0xae,
	0xc9, 0x3d, 0xe8, 0xaf, 0xe4, 0xb9, 0x28, 0x31, 0x8d, 0x1e, 0x47, 0x4f, 0x46, 0xf9, 0x16, 0xd1,
	0xcf, 0x70, 0xf7, 0x4f, 0xb2, 0x2a, 0x1d, 0x21, 0xd0, 0x5b, 0x48, 0xde, 0x92, 0xe3, 0xdc, 0xff,
	0x26, 0x29, 0x0c, 0x56, 0x68, 0x0c, 0x5b, 0x62, 0xda, 0xf1, 0x77, 0x5c, 0x41, 0x72, 0x0c, 0x71,
	0xed, 0xe9, 0x5d, 0x7f, 0xde, 0x02, 0xca, 0x61, 0xe8, 0x1d, 0xff, 0x43, 0x9e, 0x3c, 0x82, 0x31,
	0xc7, 0x5a, 0x2c, 0xb0, 0xb0, 0x4e, 0x5d, 0xdd, 0x0b, 0xed, 0xd1, 0xcc, 0x29, 0x4f, 0xa8, 0xbd,
	0xb7, 0x62, 0x47, 0x00, 0xea, 0x6b, 0xbb, 0xf4, 0x2b, 0x24, 0x5b, 0x15, 0x55, 0xba, 0x77, 0xcc,
	0x32, 0x72, 0x1f, 0x06, 0x1b, 0x83, 0xba, 0x10, 0xdc, 0xd3, 0xbb, 0x79, 0xbf, 0x81, 0x1f, 0x78,
	0x63, 0xd3, 0xca, 0xef, 0x58, 0xa5, 0xbd, 0xd6, 0xa6, 0x07, 0xe4, 0x21, 0x8c, 0xf0, 0x87, 0x12,
	0x1a, 0x0b, 0x6b, 0xd2, 0xd8, 0x0f, 0x0c, 0xdb, 0x83, 0x99, 0xa1, 0x97, 0x11, 0xc0, 0xef, 0xeb,
	0x0f, 0x8c, 0xe5, 0x3d, 0xf4, 0x38, 0xb3, 0xcc, 0xbb, 0x18, 0x4f, 0xa7, 0xd9, 0xcd, 0xb5, 0x66,
	0xe1, 0x2a, 0xb9, 0x9f, 0xa7, 0xdf, 0x20, 0x69, 0xfb, 0x99, 0x35, 0x86, 0x9b, 0x38, 0x77, 0x56,
	0x8c, 0x82, 0x15, 0x6f, 0xcc, 0xf3, 0x3a, 0x83, 0xee, 0x4e, 0x06, 0xf4, 0x23, 0xdc, 0x0e, 0x14,
	0x9a, 0x5d, 0x1f, 0xc0, 0x50, 0x98, 0xa2, 0x66, 0xe5, 0x56, 0x64, 0x98, 0x0f, 0x84, 0x39, 0x6b,
	0x60, 0x18, 0x59, 0x27, 0x8c, 0x6c, 0xfa, 0xb3, 0x03, 0x49, 0xb8, 0x15, 0xb9, 0x8c, 0x20, 0x09,
	0x5f, 0x19, 0x79, 0xb9, 0x4f, 0x1a, 0x7f, 0x3d, 0xe3, 0xc9, 0xab, 0xff, 0x19, 0x6b, 0xfe, 0x14,
	0x47, 0x64, 0x09, 0xb1, 0x27, 0x91, 0x67, 0x07, 0x14, 0xb1, 0x9e, 0x64, 0x87, 0xd5, 0x46, 0x8f,
	0x88, 0x83, 0xf1, 0x4e, 0x98, 0x64, 0xaf, 0xde, 0xc3, 0x7e, 0x27, 0x2f, 0x0e, 0x9e, 0xf1, 0xd2,
	0x6f, 0xe2, 0x2f, 0x5d, 0xa6, 0xc4, 0x79, 0xdf, 0x7f, 0x47, 0x9e, 0xff, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0x45, 0x32, 0x3d, 0x5f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// XXXLoginServerClient is the client API for XXXLoginServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XXXLoginServerClient interface {
	// 发送验证码
	SendVerifyCode(ctx context.Context, in *SendVerifyCodeReq, opts ...grpc.CallOption) (*SendVerifyCodeReply, error)
	// 登录
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error)
	// 验证token
	VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenReply, error)
}

type xXXLoginServerClient struct {
	cc *grpc.ClientConn
}

func NewXXXLoginServerClient(cc *grpc.ClientConn) XXXLoginServerClient {
	return &xXXLoginServerClient{cc}
}

func (c *xXXLoginServerClient) SendVerifyCode(ctx context.Context, in *SendVerifyCodeReq, opts ...grpc.CallOption) (*SendVerifyCodeReply, error) {
	out := new(SendVerifyCodeReply)
	err := c.cc.Invoke(ctx, "/community.interface.XXXLoginServer.XXXLoginServer/SendVerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xXXLoginServerClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/community.interface.XXXLoginServer.XXXLoginServer/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xXXLoginServerClient) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenReply, error) {
	out := new(VerifyTokenReply)
	err := c.cc.Invoke(ctx, "/community.interface.XXXLoginServer.XXXLoginServer/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXXLoginServerServer is the server API for XXXLoginServer service.
type XXXLoginServerServer interface {
	// 发送验证码
	SendVerifyCode(context.Context, *SendVerifyCodeReq) (*SendVerifyCodeReply, error)
	// 登录
	Login(context.Context, *LoginReq) (*LoginReply, error)
	// 验证token
	VerifyToken(context.Context, *VerifyTokenReq) (*VerifyTokenReply, error)
}

// UnimplementedXXXLoginServerServer can be embedded to have forward compatible implementations.
type UnimplementedXXXLoginServerServer struct {
}

func (*UnimplementedXXXLoginServerServer) SendVerifyCode(ctx context.Context, req *SendVerifyCodeReq) (*SendVerifyCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVerifyCode not implemented")
}
func (*UnimplementedXXXLoginServerServer) Login(ctx context.Context, req *LoginReq) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedXXXLoginServerServer) VerifyToken(ctx context.Context, req *VerifyTokenReq) (*VerifyTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}

func RegisterXXXLoginServerServer(s *grpc.Server, srv XXXLoginServerServer) {
	s.RegisterService(&_XXXLoginServer_serviceDesc, srv)
}

func _XXXLoginServer_SendVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerifyCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXLoginServerServer).SendVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/community.interface.XXXLoginServer.XXXLoginServer/SendVerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXLoginServerServer).SendVerifyCode(ctx, req.(*SendVerifyCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XXXLoginServer_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXLoginServerServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/community.interface.XXXLoginServer.XXXLoginServer/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXLoginServerServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XXXLoginServer_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXLoginServerServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/community.interface.XXXLoginServer.XXXLoginServer/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXLoginServerServer).VerifyToken(ctx, req.(*VerifyTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _XXXLoginServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "community.interface.XXXLoginServer.XXXLoginServer",
	HandlerType: (*XXXLoginServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVerifyCode",
			Handler:    _XXXLoginServer_SendVerifyCode_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _XXXLoginServer_Login_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _XXXLoginServer_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXXLoginServer.proto",
}
