// Code generated by protoc-gen-go. DO NOT EDIT.
// source: XXXUserServer.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NoArgReq
type NoArgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoArgRequest) Reset()         { *m = NoArgRequest{} }
func (m *NoArgRequest) String() string { return proto.CompactTextString(m) }
func (*NoArgRequest) ProtoMessage()    {}
func (*NoArgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11cee4ab837c3f70, []int{0}
}

func (m *NoArgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoArgRequest.Unmarshal(m, b)
}
func (m *NoArgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoArgRequest.Marshal(b, m, deterministic)
}
func (m *NoArgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoArgRequest.Merge(m, src)
}
func (m *NoArgRequest) XXX_Size() int {
	return xxx_messageInfo_NoArgRequest.Size(m)
}
func (m *NoArgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoArgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoArgRequest proto.InternalMessageInfo

// NoReply
type NoReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoReply) Reset()         { *m = NoReply{} }
func (m *NoReply) String() string { return proto.CompactTextString(m) }
func (*NoReply) ProtoMessage()    {}
func (*NoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11cee4ab837c3f70, []int{1}
}

func (m *NoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoReply.Unmarshal(m, b)
}
func (m *NoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoReply.Marshal(b, m, deterministic)
}
func (m *NoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoReply.Merge(m, src)
}
func (m *NoReply) XXX_Size() int {
	return xxx_messageInfo_NoReply.Size(m)
}
func (m *NoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NoReply.DiscardUnknown(m)
}

var xxx_messageInfo_NoReply proto.InternalMessageInfo

type GetUserNameReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserNameReply) Reset()         { *m = GetUserNameReply{} }
func (m *GetUserNameReply) String() string { return proto.CompactTextString(m) }
func (*GetUserNameReply) ProtoMessage()    {}
func (*GetUserNameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11cee4ab837c3f70, []int{2}
}

func (m *GetUserNameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserNameReply.Unmarshal(m, b)
}
func (m *GetUserNameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserNameReply.Marshal(b, m, deterministic)
}
func (m *GetUserNameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserNameReply.Merge(m, src)
}
func (m *GetUserNameReply) XXX_Size() int {
	return xxx_messageInfo_GetUserNameReply.Size(m)
}
func (m *GetUserNameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserNameReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserNameReply proto.InternalMessageInfo

func (m *GetUserNameReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*NoArgRequest)(nil), "community.interface.XXXUserServer.NoArgRequest")
	proto.RegisterType((*NoReply)(nil), "community.interface.XXXUserServer.NoReply")
	proto.RegisterType((*GetUserNameReply)(nil), "community.interface.XXXUserServer.GetUserNameReply")
}

func init() { proto.RegisterFile("XXXUserServer.proto", fileDescriptor_11cee4ab837c3f70) }

var fileDescriptor_11cee4ab837c3f70 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x8e, 0x88, 0x88, 0x08,
	0x2d, 0x4e, 0x2d, 0x0a, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x52, 0x4c, 0xce, 0xcf, 0xcd, 0x2d, 0xcd, 0xcb, 0x2c, 0xa9, 0xd4, 0xcb, 0xcc, 0x2b, 0x49, 0x2d,
	0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x43, 0x51, 0xa8, 0xc4, 0xc7, 0xc5, 0xe3, 0x97, 0xef, 0x58, 0x94,
	0x1e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0xa2, 0xc4, 0xc9, 0xc5, 0xee, 0x97, 0x1f, 0x94, 0x5a,
	0x90, 0x53, 0xa9, 0xa4, 0xc6, 0x25, 0xe0, 0x9e, 0x5a, 0x02, 0x52, 0xeb, 0x97, 0x98, 0x9b, 0x0a,
	0x16, 0x13, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0x8d, 0xda, 0x18, 0xb9, 0x78, 0x51, 0x0c, 0x15, 0x2a, 0xe5, 0xe2, 0x46, 0xd2, 0x29,
	0xa4, 0xaf, 0x47, 0xd0, 0x1d, 0x7a, 0xc8, 0x8e, 0x90, 0x32, 0x26, 0x42, 0x03, 0xba, 0xd3, 0x94,
	0x18, 0x9c, 0x58, 0xa3, 0x98, 0x13, 0x0b, 0x32, 0x93, 0xd8, 0xc0, 0x9e, 0x37, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x54, 0x91, 0x02, 0x1c, 0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// XXXUserServerClient is the client API for XXXUserServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XXXUserServerClient interface {
	GetUserName(ctx context.Context, in *NoArgRequest, opts ...grpc.CallOption) (*GetUserNameReply, error)
}

type xXXUserServerClient struct {
	cc *grpc.ClientConn
}

func NewXXXUserServerClient(cc *grpc.ClientConn) XXXUserServerClient {
	return &xXXUserServerClient{cc}
}

func (c *xXXUserServerClient) GetUserName(ctx context.Context, in *NoArgRequest, opts ...grpc.CallOption) (*GetUserNameReply, error) {
	out := new(GetUserNameReply)
	err := c.cc.Invoke(ctx, "/community.interface.XXXUserServer.XXXUserServer/GetUserName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXXUserServerServer is the server API for XXXUserServer service.
type XXXUserServerServer interface {
	GetUserName(context.Context, *NoArgRequest) (*GetUserNameReply, error)
}

// UnimplementedXXXUserServerServer can be embedded to have forward compatible implementations.
type UnimplementedXXXUserServerServer struct {
}

func (*UnimplementedXXXUserServerServer) GetUserName(ctx context.Context, req *NoArgRequest) (*GetUserNameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserName not implemented")
}

func RegisterXXXUserServerServer(s *grpc.Server, srv XXXUserServerServer) {
	s.RegisterService(&_XXXUserServer_serviceDesc, srv)
}

func _XXXUserServer_GetUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoArgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXUserServerServer).GetUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/community.interface.XXXUserServer.XXXUserServer/GetUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXUserServerServer).GetUserName(ctx, req.(*NoArgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _XXXUserServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "community.interface.XXXUserServer.XXXUserServer",
	HandlerType: (*XXXUserServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserName",
			Handler:    _XXXUserServer_GetUserName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXXUserServer.proto",
}
