// Code generated by protoc-gen-go. DO NOT EDIT.
// source: XXXSMS.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NoArgReq
type NoArgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoArgRequest) Reset()         { *m = NoArgRequest{} }
func (m *NoArgRequest) String() string { return proto.CompactTextString(m) }
func (*NoArgRequest) ProtoMessage()    {}
func (*NoArgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81df894713fe0e27, []int{0}
}

func (m *NoArgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoArgRequest.Unmarshal(m, b)
}
func (m *NoArgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoArgRequest.Marshal(b, m, deterministic)
}
func (m *NoArgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoArgRequest.Merge(m, src)
}
func (m *NoArgRequest) XXX_Size() int {
	return xxx_messageInfo_NoArgRequest.Size(m)
}
func (m *NoArgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoArgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoArgRequest proto.InternalMessageInfo

// NoReply
type NoReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoReply) Reset()         { *m = NoReply{} }
func (m *NoReply) String() string { return proto.CompactTextString(m) }
func (*NoReply) ProtoMessage()    {}
func (*NoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_81df894713fe0e27, []int{1}
}

func (m *NoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoReply.Unmarshal(m, b)
}
func (m *NoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoReply.Marshal(b, m, deterministic)
}
func (m *NoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoReply.Merge(m, src)
}
func (m *NoReply) XXX_Size() int {
	return xxx_messageInfo_NoReply.Size(m)
}
func (m *NoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NoReply.DiscardUnknown(m)
}

var xxx_messageInfo_NoReply proto.InternalMessageInfo

type SendMsgReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgReq) Reset()         { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()    {}
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81df894713fe0e27, []int{2}
}

func (m *SendMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgReq.Unmarshal(m, b)
}
func (m *SendMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgReq.Marshal(b, m, deterministic)
}
func (m *SendMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgReq.Merge(m, src)
}
func (m *SendMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendMsgReq.Size(m)
}
func (m *SendMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgReq proto.InternalMessageInfo

func (m *SendMsgReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SendMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*NoArgRequest)(nil), "community.service.XXXSMS.NoArgRequest")
	proto.RegisterType((*NoReply)(nil), "community.service.XXXSMS.NoReply")
	proto.RegisterType((*SendMsgReq)(nil), "community.service.XXXSMS.SendMsgReq")
}

func init() { proto.RegisterFile("XXXSMS.proto", fileDescriptor_81df894713fe0e27) }

var fileDescriptor_81df894713fe0e27 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x89, 0x88, 0x88, 0x08,
	0xf6, 0x0d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xce, 0xcf, 0xcd, 0x2d, 0xcd,
	0xcb, 0x2c, 0xa9, 0xd4, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x83, 0xc8, 0x2b, 0xf1,
	0x71, 0xf1, 0xf8, 0xe5, 0x3b, 0x16, 0xa5, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x71,
	0x72, 0xb1, 0xfb, 0xe5, 0x07, 0xa5, 0x16, 0xe4, 0x54, 0x2a, 0x99, 0x71, 0x71, 0x05, 0xa7, 0xe6,
	0xa5, 0xf8, 0x16, 0x83, 0x24, 0x85, 0xc4, 0xb8, 0xd8, 0x72, 0xf3, 0x93, 0x32, 0x73, 0x52, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09,
	0x26, 0xb0, 0x20, 0x88, 0x69, 0x14, 0xc7, 0xc5, 0x06, 0x31, 0x5c, 0x28, 0x84, 0x8b, 0x1d, 0x6a,
	0x82, 0x90, 0x8a, 0x1e, 0x2e, 0x27, 0xe8, 0x21, 0x2c, 0x91, 0x52, 0xc4, 0xad, 0x0a, 0xe6, 0x2a,
	0x06, 0x27, 0xd6, 0x28, 0xe6, 0xc4, 0x82, 0xcc, 0x24, 0x36, 0xb0, 0xd7, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0x80, 0xaf, 0xec, 0xea, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// XXXSMSClient is the client API for XXXSMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XXXSMSClient interface {
	// 发送短信
	SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*NoReply, error)
}

type xXXSMSClient struct {
	cc *grpc.ClientConn
}

func NewXXXSMSClient(cc *grpc.ClientConn) XXXSMSClient {
	return &xXXSMSClient{cc}
}

func (c *xXXSMSClient) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*NoReply, error) {
	out := new(NoReply)
	err := c.cc.Invoke(ctx, "/community.service.XXXSMS.XXXSMS/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXXSMSServer is the server API for XXXSMS service.
type XXXSMSServer interface {
	// 发送短信
	SendMsg(context.Context, *SendMsgReq) (*NoReply, error)
}

// UnimplementedXXXSMSServer can be embedded to have forward compatible implementations.
type UnimplementedXXXSMSServer struct {
}

func (*UnimplementedXXXSMSServer) SendMsg(ctx context.Context, req *SendMsgReq) (*NoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}

func RegisterXXXSMSServer(s *grpc.Server, srv XXXSMSServer) {
	s.RegisterService(&_XXXSMS_serviceDesc, srv)
}

func _XXXSMS_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXSMSServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/community.service.XXXSMS.XXXSMS/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXSMSServer).SendMsg(ctx, req.(*SendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _XXXSMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "community.service.XXXSMS.XXXSMS",
	HandlerType: (*XXXSMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _XXXSMS_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXXSMS.proto",
}
