// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserCenter.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NoArgReq
type NoArgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoArgRequest) Reset()         { *m = NoArgRequest{} }
func (m *NoArgRequest) String() string { return proto.CompactTextString(m) }
func (*NoArgRequest) ProtoMessage()    {}
func (*NoArgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98e8acf3c37663a, []int{0}
}

func (m *NoArgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoArgRequest.Unmarshal(m, b)
}
func (m *NoArgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoArgRequest.Marshal(b, m, deterministic)
}
func (m *NoArgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoArgRequest.Merge(m, src)
}
func (m *NoArgRequest) XXX_Size() int {
	return xxx_messageInfo_NoArgRequest.Size(m)
}
func (m *NoArgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoArgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoArgRequest proto.InternalMessageInfo

// NoReply
type NoReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoReply) Reset()         { *m = NoReply{} }
func (m *NoReply) String() string { return proto.CompactTextString(m) }
func (*NoReply) ProtoMessage()    {}
func (*NoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98e8acf3c37663a, []int{1}
}

func (m *NoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoReply.Unmarshal(m, b)
}
func (m *NoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoReply.Marshal(b, m, deterministic)
}
func (m *NoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoReply.Merge(m, src)
}
func (m *NoReply) XXX_Size() int {
	return xxx_messageInfo_NoReply.Size(m)
}
func (m *NoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NoReply.DiscardUnknown(m)
}

var xxx_messageInfo_NoReply proto.InternalMessageInfo

type GetUserIDByMobileReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AutoCreate           bool     `protobuf:"varint,2,opt,name=autoCreate,proto3" json:"autoCreate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDByMobileReq) Reset()         { *m = GetUserIDByMobileReq{} }
func (m *GetUserIDByMobileReq) String() string { return proto.CompactTextString(m) }
func (*GetUserIDByMobileReq) ProtoMessage()    {}
func (*GetUserIDByMobileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98e8acf3c37663a, []int{2}
}

func (m *GetUserIDByMobileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDByMobileReq.Unmarshal(m, b)
}
func (m *GetUserIDByMobileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDByMobileReq.Marshal(b, m, deterministic)
}
func (m *GetUserIDByMobileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDByMobileReq.Merge(m, src)
}
func (m *GetUserIDByMobileReq) XXX_Size() int {
	return xxx_messageInfo_GetUserIDByMobileReq.Size(m)
}
func (m *GetUserIDByMobileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDByMobileReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDByMobileReq proto.InternalMessageInfo

func (m *GetUserIDByMobileReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetUserIDByMobileReq) GetAutoCreate() bool {
	if m != nil {
		return m.AutoCreate
	}
	return false
}

type GetUserIDByMobileReply struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsNew                bool     `protobuf:"varint,2,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDByMobileReply) Reset()         { *m = GetUserIDByMobileReply{} }
func (m *GetUserIDByMobileReply) String() string { return proto.CompactTextString(m) }
func (*GetUserIDByMobileReply) ProtoMessage()    {}
func (*GetUserIDByMobileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98e8acf3c37663a, []int{3}
}

func (m *GetUserIDByMobileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDByMobileReply.Unmarshal(m, b)
}
func (m *GetUserIDByMobileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDByMobileReply.Marshal(b, m, deterministic)
}
func (m *GetUserIDByMobileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDByMobileReply.Merge(m, src)
}
func (m *GetUserIDByMobileReply) XXX_Size() int {
	return xxx_messageInfo_GetUserIDByMobileReply.Size(m)
}
func (m *GetUserIDByMobileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDByMobileReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDByMobileReply proto.InternalMessageInfo

func (m *GetUserIDByMobileReply) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserIDByMobileReply) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

func init() {
	proto.RegisterType((*NoArgRequest)(nil), "community.service.UserCenter.NoArgRequest")
	proto.RegisterType((*NoReply)(nil), "community.service.UserCenter.NoReply")
	proto.RegisterType((*GetUserIDByMobileReq)(nil), "community.service.UserCenter.GetUserIDByMobileReq")
	proto.RegisterType((*GetUserIDByMobileReply)(nil), "community.service.UserCenter.GetUserIDByMobileReply")
}

func init() { proto.RegisterFile("UserCenter.proto", fileDescriptor_f98e8acf3c37663a) }

var fileDescriptor_f98e8acf3c37663a = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x2d, 0x4e, 0x2d,
	0x72, 0x4e, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x49, 0xce,
	0xcf, 0xcd, 0x2d, 0xcd, 0xcb, 0x2c, 0xa9, 0xd4, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5,
	0x43, 0xa8, 0x51, 0xe2, 0xe3, 0xe2, 0xf1, 0xcb, 0x77, 0x2c, 0x4a, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x51, 0xe2, 0xe4, 0x62, 0xf7, 0xcb, 0x0f, 0x4a, 0x2d, 0xc8, 0xa9, 0x54, 0xf2, 0xe3,
	0x12, 0x71, 0x4f, 0x2d, 0x01, 0xa9, 0xf5, 0x74, 0x71, 0xaa, 0xf4, 0xcd, 0x4f, 0xca, 0xcc, 0x49,
	0x0d, 0x4a, 0x2d, 0x14, 0x12, 0xe3, 0x62, 0xcb, 0x05, 0x73, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xa0, 0x3c, 0x21, 0x39, 0x2e, 0xae, 0xc4, 0xd2, 0x92, 0x7c, 0xe7, 0xa2, 0xd4, 0xc4, 0x92,
	0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x24, 0x11, 0x25, 0x0f, 0x2e, 0x31, 0x2c, 0xe6,
	0x15, 0xe4, 0x54, 0x0a, 0x89, 0x73, 0xb1, 0x97, 0x16, 0xa7, 0x16, 0xc5, 0x67, 0xa6, 0x80, 0x8d,
	0x64, 0x0e, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x44, 0xb9, 0xd8, 0x32, 0x8b, 0xe3, 0xf3, 0x52,
	0xcb, 0xa1, 0xc6, 0xb1, 0x66, 0x16, 0xfb, 0xa5, 0x96, 0x1b, 0xf5, 0x32, 0x72, 0x71, 0x21, 0xfc,
	0x20, 0x54, 0xcf, 0x25, 0x88, 0x61, 0xb0, 0x90, 0x91, 0x1e, 0x3e, 0x7f, 0xeb, 0x61, 0xf3, 0x99,
	0x94, 0x09, 0xc9, 0x7a, 0x40, 0xe1, 0xc4, 0xe0, 0xc4, 0x1a, 0xc5, 0x9c, 0x58, 0x90, 0x99, 0xc4,
	0x06, 0x0e, 0x70, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x23, 0xe3, 0x29, 0x84, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserCenterClient is the client API for UserCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserCenterClient interface {
	// 发送短信
	GetUserIDByMobile(ctx context.Context, in *GetUserIDByMobileReq, opts ...grpc.CallOption) (*GetUserIDByMobileReply, error)
}

type userCenterClient struct {
	cc *grpc.ClientConn
}

func NewUserCenterClient(cc *grpc.ClientConn) UserCenterClient {
	return &userCenterClient{cc}
}

func (c *userCenterClient) GetUserIDByMobile(ctx context.Context, in *GetUserIDByMobileReq, opts ...grpc.CallOption) (*GetUserIDByMobileReply, error) {
	out := new(GetUserIDByMobileReply)
	err := c.cc.Invoke(ctx, "/community.service.UserCenter.UserCenter/GetUserIDByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCenterServer is the server API for UserCenter service.
type UserCenterServer interface {
	// 发送短信
	GetUserIDByMobile(context.Context, *GetUserIDByMobileReq) (*GetUserIDByMobileReply, error)
}

// UnimplementedUserCenterServer can be embedded to have forward compatible implementations.
type UnimplementedUserCenterServer struct {
}

func (*UnimplementedUserCenterServer) GetUserIDByMobile(ctx context.Context, req *GetUserIDByMobileReq) (*GetUserIDByMobileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIDByMobile not implemented")
}

func RegisterUserCenterServer(s *grpc.Server, srv UserCenterServer) {
	s.RegisterService(&_UserCenter_serviceDesc, srv)
}

func _UserCenter_GetUserIDByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIDByMobileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCenterServer).GetUserIDByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/community.service.UserCenter.UserCenter/GetUserIDByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCenterServer).GetUserIDByMobile(ctx, req.(*GetUserIDByMobileReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "community.service.UserCenter.UserCenter",
	HandlerType: (*UserCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserIDByMobile",
			Handler:    _UserCenter_GetUserIDByMobile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "UserCenter.proto",
}
